apiVersion: apps/v1
kind: Deployment
metadata:
  name: wema
  labels:
    app: wema
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wema
  template:
    metadata:
      labels:
        app: wema
    spec:
      containers:
        - name: kubenginx
          image: wemadevops/kubenginx:2.0.0
          resources: {}
