apiVersion: v1
kind: Service
metadata:
  name: my-svc
  labels:
    app: wema
spec:
  selector:
    app: wema
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
